"""
evaluate_outcomes.py — CLI script for evaluating hypotheses against actual outcomes.

Read-only by default. Requires --commit to write to scientific.db.
"""
import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Any

from core.scientific.scientific_store import ScientificStore
from core.scientific.outcome_evaluator import (
    evaluate_hypotheses,
    parse_hypothesis_id,
    print_evaluation_report,
)


REPORT_DIR = Path(__file__).resolve().parent.parent / "_project-memory" / "evaluations"


def save_markdown_report(result: Dict[str, Any]) -> str:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    mode = "dry_run" if result.get("dry_run") else "committed"
    path = REPORT_DIR / f"outcome_evaluation_{mode}_{ts}.md"

    lines = [
        "# Outcome Evaluation Report",
        "",
        f"**Timestamp**: {datetime.now(timezone.utc).isoformat()}",
        f"**Mode**: {'Dry Run' if result.get('dry_run') else 'Committed'}",
        f"**Hypotheses available**: {result.get('total_hypotheses')}",
        f"**Hypotheses evaluated**: {result.get('evaluated')}",
        "",
        "## Verdict Distribution",
        "",
    ]
    verdicts: Dict[str, int] = {}
    for r in result.get("results", []):
        v = r["verdict"]
        verdicts[v] = verdicts.get(v, 0) + 1
    for v, c in sorted(verdicts.items(), key=lambda x: -x[1]):
        lines.append(f"- **{v}**: {c}")
    lines.append("")

    lines.append("## Detailed Results")
    lines.append("")
    lines.append("| Hypothesis | Verdict | Score | Error | Actual Outcome |")
    lines.append("|---|---|---|---|---|")
    for r in result.get("results", []):
        lines.append(
            f"| {r['hypothesis_title'][:40]} | {r['verdict']} | "
            f"{r['outcome_score']} | {r.get('error_type', '')} | "
            f"{r['actual_outcome'][:40]} |"
        )
    lines.append("")

    if result.get("dry_run"):
        lines.append("*Read-only. Pass --commit to persist.*")
    lines.append("")
    lines.append("---")
    lines.append("*Report generated by evaluate_outcomes.py*")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"[evaluate] Report saved: {path}")
    return str(path)


def main():
    parser = argparse.ArgumentParser(
        description="Evaluate hypotheses against actual outcomes"
    )
    parser.add_argument("--hypothesis", "-H", default="all",
                        help="Hypothesis ID or prefix (default: all)")
    parser.add_argument("--actual-outcome", "-O", required=True,
                        help="Actual outcome text for evaluation")
    parser.add_argument("--scientific-db", default="scientific.db",
                        help="Path to scientific.db")
    parser.add_argument("--commit", action="store_true",
                        help="Write comparisons to scientific.db")
    parser.add_argument("--save", action="store_true",
                        help="Save markdown report")
    args = parser.parse_args()

    store = ScientificStore(args.scientific_db)

    hyp_id = parse_hypothesis_id(args.hypothesis, store)
    if hyp_id is None:
        sys.exit(1)

    actual_outcomes = {hyp_id: args.actual_outcome}

    result = evaluate_hypotheses(
        hypothesis_ids=[hyp_id] if hyp_id != "all" else [],
        actual_outcomes=actual_outcomes,
        store=store,
        dry_run=not args.commit,
    )

    print_evaluation_report(result)

    if args.save:
        save_markdown_report(result)


if __name__ == "__main__":
    main()
